global:  # Sección que define la configuración global de Prometheus.
  scrape_interval:     5s  # Establece el intervalo de recolección de métricas en 5 segundos. El valor por defecto es 1 minuto.
  evaluation_interval: 5s  # Establece el intervalo de evaluación de reglas en 5 segundos. El valor por defecto es 1 minuto.

scrape_configs:  # Sección donde se configuran los trabajos de recolección de métricas.
  - job_name: 'prometheus'  # Define un trabajo llamado 'prometheus'.
    static_configs:  # Configuración estática para los objetivos de recolección.
    - targets: ['prometheus:9090']  # Especifica el objetivo a recolectar, que es el servicio de Prometheus en el puerto 9090.

  - job_name: 'cadvisor'  # Define un trabajo llamado 'cadvisor'.
    static_configs:  # Configuración estática para los objetivos de recolección.
    - targets: ['cadvisor:8080']  # Especifica el objetivo a recolectar, que es el servicio de cAdvisor en el puerto 8080.

  - job_name: 'node_exporter'  # Define un trabajo llamado 'node_exporter'.
    static_configs:  # Configuración estática para los objetivos de recolección.
    - targets: ['node_exporter:9100']  # Especifica el objetivo a recolectar, que es el servicio de Node Exporter en el puerto 9100.

  - job_name: 'app_example'  # Define un trabajo llamado 'app_example'.
    static_configs:  # Configuración estática para los objetivos de recolección.
    - targets: ['app_example:8080']  # Especifica el objetivo a recolectar, que es el servicio de ejemplo en el puerto 8080.
    #metrics_path: '/metrics'  # (Opcional) Especifica la ruta de métricas a recolectar; está comentada.
    #metrics_path: '/prometheus'  # (Opcional) Especifica otra ruta de métricas a recolectar; también está comentada.

