export const metadata = {
  title: 'Monitoreo de Desarrollo',
  description: 'Generated by Pepe Adox',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  )
}
