version: '3'

services:
  monitoreodeservidoresfront:
    platform: amd64
    container_name: monitoreo_de_servidores_web
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
networks:
  default:
    external: true
    name: nginx-proxy-manager_default